# Generated by Django 6.0 on 2026-07-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('other', 'Other')], default='bank', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_archived', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
