# Generated by Django 6.0 on 2026-08-02 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('currencies', '0002_initial'),
        ('workspaces', '0002_workspace_default_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_default_for_currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_for_currency', True)), fields=('workspace', 'currency'), name='one_default_account_per_currency'),
        ),
    ]
