# Generated by Django 6.0 on 2026-07-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_add_workspace_to_budget'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budget',
            table='legacy_budgets',
        ),
        # PostgreSQL does not rename indexes on table rename; free their
        # 'budgets_*' names so the new budgeting.Budget table can use them.
        migrations.RunSQL(
            sql="""
            DO $$
            DECLARE r record;
            BEGIN
              FOR r IN SELECT indexname FROM pg_indexes
                       WHERE tablename = 'legacy_budgets' AND indexname LIKE 'budgets_%'
              LOOP
                EXECUTE format('ALTER INDEX %I RENAME TO %I', r.indexname, 'legacy_' || r.indexname);
              END LOOP;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
