# Generated by Django 6.0 on 2026-08-22 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planned_transactions', '0002_initial'),
        ('workspaces', '0002_workspace_default_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedTransactionIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planned_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_keys', to='planned_transactions.plannedtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_transaction_idempotency_keys', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_transaction_idempotency_keys', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'planned_transaction_idempotency_keys',
                'indexes': [models.Index(fields=['created_at'], name='planned_tra_created_bf8921_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'user', 'workspace'), name='unique_planned_key_per_user_workspace')],
            },
        ),
    ]
