# Generated by Django 6.0 on 2026-08-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_initial'),
        ('currencies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='budgeting.budget')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_currencies', to='currencies.currency')),
            ],
            options={
                'verbose_name_plural': 'budget currencies',
                'db_table': 'budget_currencies',
                'ordering': ['position', 'id'],
                'unique_together': {('budget', 'currency')},
            },
        ),
        migrations.RemoveField(
            model_name='budget',
            name='display_currency',
        ),
    ]
