# Generated by Django 6.0 on 2026-07-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=8)),
                ('decimals', models.PositiveSmallIntegerField(default=2)),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currencies_catalog',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'workspace currencies',
                'db_table': 'workspace_currencies',
            },
        ),
    ]
