# Generated by Django 6.0 on 2026-07-07 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_migrate_to_workspace_scoped_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=8)),
                ('decimals', models.PositiveSmallIntegerField(default=2)),
                ('is_custom', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_currencies', to='workspaces.workspace')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'db_table': 'currencies_catalog',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enablements', to='currencies.currency')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_currencies', to='workspaces.workspace')),
            ],
            options={
                'verbose_name_plural': 'workspace currencies',
                'db_table': 'workspace_currencies',
            },
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('code',), name='uniq_global_currency_code'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('workspace', 'code'), name='uniq_custom_currency_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_custom', True), ('workspace__isnull', False)), models.Q(('is_custom', False), ('workspace__isnull', True)), _connector='OR'), name='custom_currency_has_workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacecurrency',
            unique_together={('workspace', 'currency')},
        ),
    ]
