# Generated by Django 6.0 on 2026-07-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_currencies', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='workspacecurrency',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enablements', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='workspacecurrency',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_currencies', to='workspaces.workspace'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('code',), name='uniq_global_currency_code'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('workspace', 'code'), name='uniq_custom_currency_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_custom', True), ('workspace__isnull', False)), models.Q(('is_custom', False), ('workspace__isnull', True)), _connector='OR'), name='custom_currency_has_workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacecurrency',
            unique_together={('workspace', 'currency')},
        ),
    ]
