blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/Owlgarth/finances/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/Owlgarth/finances/tree/main/docs
    about: View the project documentation
