# Generated by Django 6.0 on 2026-07-07 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workspaces', '0003_migrate_to_workspace_scoped_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounts.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounts.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'transfers',
                'indexes': [models.Index(fields=['from_account', 'date'], name='transfers_from_ac_8b7a60_idx'), models.Index(fields=['to_account', 'date'], name='transfers_to_acco_164f5c_idx'), models.Index(fields=['workspace', 'date'], name='transfers_workspa_f9488b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_account', models.F('to_account')), _negated=True), name='transfer_accounts_differ')],
            },
        ),
    ]
