# Generated by Django 6.0 on 2026-07-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactionattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionattachment',
            name='extraction_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transactionattachment',
            name='extraction_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionattachment',
            name='extraction_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='none', max_length=20),
        ),
    ]
