# Generated by Django 6.0 on 2026-07-20 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactionattachment_extraction_error_and_more'),
        ('workspaces', '0002_workspace_default_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_keys', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_idempotency_keys', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_idempotency_keys', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'transaction_idempotency_keys',
                'indexes': [models.Index(fields=['created_at'], name='transaction_created_3f4fd3_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'user'), name='unique_key_per_user')],
            },
        ),
    ]
