# Generated by Django 6.0 on 2026-07-31 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transactionidempotencykey'),
        ('workspaces', '0002_workspace_default_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactionidempotencykey',
            name='unique_key_per_user',
        ),
        migrations.AddConstraint(
            model_name='transactionidempotencykey',
            constraint=models.UniqueConstraint(fields=('key', 'user', 'workspace'), name='unique_key_per_user_workspace'),
        ),
    ]
