# Generated by Django 6.0 on 2026-10-08 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_is_default_for_currency_and_more"),
        ("categories", "0002_initial"),
        ("currencies", "0003_workspacecurrency_position"),
        ("transactions", "0009_transaction_note"),
        ("workspaces", "0002_workspace_default_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="source_transaction",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_adjustments",
                to="transactions.transaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("source_transaction",), name="one_adjustment_per_source"
            ),
        ),
    ]
