# Generated by Django 6.0 on 2026-10-07 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_adjustments', to='transactions.transaction'),
        ),
    ]
