# Generated by Django 6.0 on 2026-08-21 15:25

from django.db import migrations, models
from django.db.models import F


def backfill_password_changed_at(apps, schema_editor):
    """Backfill with created_at, NOT now().

    now() would invalidate every outstanding refresh token in production on
    deploy (iat < stamp). created_at keeps all existing tokens valid — they
    were necessarily issued after account creation. Rows created via
    create_user between migration generation and deploy already carry the
    stamp from the set_password override; the filter only touches nulls.
    """
    User = apps.get_model('users', 'User')
    User.objects.filter(password_changed_at__isnull=True).update(password_changed_at=F('created_at'))


def unbackfill_password_changed_at(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.update(password_changed_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_password_changed_at, unbackfill_password_changed_at),
    ]
