# Generated by Django 6.0 on 2026-08-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertwofactor',
            name='last_used_timestep',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
