# Generated by Django 6.0 on 2026-08-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usertwofactor_last_used_timestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(default='en', help_text='UI language code from the language registry', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='number_format',
            field=models.CharField(default='en', help_text='Number and date formatting style from the language registry', max_length=10),
        ),
    ]
